# Generated by Django 5.2.1 on 2025-06-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcycling_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcyclingrequest',
            name='ai_labels',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
